// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW83SYX3iEdTJFkrvnwWkCYzcnb7r8_Gk',
    appId: '1:98614404819:android:d78d44bf4d9d115ab5d626',
    messagingSenderId: '98614404819',
    projectId: 'pantryscanner-eb88c',
    storageBucket: 'pantryscanner-eb88c.firebasestorage.app',
  );
}